"""Vocabulary used by the generator: categories, product text and review phrases.

Kept separate from generate_data.py so you can extend the catalog without
touching the generation logic. Everything here is invented; brands and models
are fictional.
"""

DEPARTMENTS = ["Footwear", "Clothing", "Camping", "Packs", "Electronics", "Climbing"]

# (CategoryID, CategoryName, Department, singular noun, (min price, max price))
CATEGORIES = [
    (1, "Hiking Boots", "Footwear", "Hiking Boot", (119, 289)),
    (2, "Trail Runners", "Footwear", "Trail Runner", (89, 189)),
    (3, "Sandals", "Footwear", "Sandal", (39, 99)),
    (4, "Rain Jackets", "Clothing", "Rain Jacket", (99, 399)),
    (5, "Insulated Jackets", "Clothing", "Insulated Jacket", (149, 449)),
    (6, "Base Layers", "Clothing", "Base Layer", (35, 119)),
    (7, "Hiking Pants", "Clothing", "Hiking Pant", (59, 149)),
    (8, "Tents", "Camping", "Tent", (179, 799)),
    (9, "Sleeping Bags", "Camping", "Sleeping Bag", (99, 549)),
    (10, "Sleeping Pads", "Camping", "Sleeping Pad", (49, 219)),
    (11, "Stoves", "Camping", "Stove", (39, 179)),
    (12, "Daypacks", "Packs", "Daypack", (49, 159)),
    (13, "Backpacking Packs", "Packs", "Backpacking Pack", (159, 399)),
    (14, "Headlamps", "Electronics", "Headlamp", (19, 119)),
    (15, "GPS Devices", "Electronics", "GPS Device", (149, 599)),
    (16, "Harnesses", "Climbing", "Harness", (55, 159)),
    (17, "Ropes", "Climbing", "Rope", (129, 329)),
    (18, "Water Filters", "Camping", "Water Filter", (25, 129)),
]

BRANDS = [
    "Summitline", "Ridgeway Co", "Alpenfox", "NorthCairn",
    "Tidewater", "Granite & Pine", "Lumen Peak", "Driftwood Gear",
]

MODEL_WORDS = [
    "Talus", "Scree", "Cirque", "Arete", "Cairn", "Couloir", "Moraine", "Tarn",
    "Col", "Bivy", "Switchback", "Krummholz", "Saddle", "Gully", "Esker", "Fjell",
    "Tundra", "Taiga", "Ridgeline", "Basecamp", "Traverse", "Summit", "Larch", "Birch",
]

MODEL_SUFFIX = ["", " GTX", " Lite", " Pro", " 2", " Mid", " UL", " Trek", " Plus", " XT"]

COLORS = ["Black", "Slate", "Moss", "Rust", "Glacier Blue", "Sand", "Ember", "Fjord", "Olive"]

# Feature phrases used to build product descriptions (pick several per product).
DESCRIPTION_FEATURES = {
    1: ["waterproof breathable membrane keeps feet dry on wet trails",
        "stiff Vibram-style outsole grips loose rock and mud",
        "padded high-cut collar gives ankle support under a heavy pack",
        "full-grain leather upper resists abrasion on scree",
        "cushioned midsole reduces fatigue on long descents",
        "rubber toe cap protects against rocks and roots"],
    2: ["lightweight mesh upper drains quickly after stream crossings",
        "aggressive 5 mm lugs bite into soft forest trails",
        "rock plate shields the foot on technical terrain",
        "responsive foam midsole for fast and light days",
        "quick-lace system for easy on and off at aid stations"],
    3: ["quick-drying straps for river walks and beach days",
        "contoured footbed with arch support",
        "sticky rubber sole for wet rocks",
        "adjustable heel strap keeps the sandal secure"],
    4: ["three-layer waterproof shell with fully taped seams",
        "pit zips dump heat on steep climbs",
        "helmet-compatible hood with a stiffened brim",
        "packs into its own chest pocket",
        "breathable fabric for stop-and-go hiking in the rain"],
    5: ["recycled down insulation with high warmth-to-weight ratio",
        "synthetic fill stays warm when damp",
        "packable puffy for cold belays and winter camp evenings",
        "windproof ripstop face fabric",
        "insulated hood traps heat in freezing wind"],
    6: ["merino wool blend regulates temperature and resists odor",
        "flatlock seams prevent chafing under pack straps",
        "moisture-wicking fabric dries fast during sweaty climbs",
        "thumb loops keep sleeves in place"],
    7: ["stretch nylon allows a full range of motion when scrambling",
        "zip-off legs convert to shorts",
        "durable water repellent finish sheds light rain",
        "reinforced knees and seat for rough terrain"],
    8: ["freestanding double-wall design pitches in minutes",
        "two doors and two vestibules for gear storage",
        "aluminum poles handle strong wind on exposed ridges",
        "silicone-coated fly sheds heavy rain",
        "four-season build for snow camping",
        "ultralight single-wall shelter for fast-and-light trips"],
    9: ["comfort rating suitable for shoulder-season nights",
        "water-resistant down for damp tent conditions",
        "draft collar and hood cinch keep warmth in",
        "packs down small into a compression sack",
        "rated for sub-zero winter camping"],
    10: ["insulated air pad with a high R-value for frozen ground",
         "self-inflating foam core for comfort and durability",
         "quiet fabric that does not crinkle at night",
         "fast-inflation valve with a pump sack"],
    11: ["canister stove boils a liter of water in about three minutes",
         "piezo igniter for easy lighting",
         "windscreen improves efficiency in breezy conditions",
         "integrated pot system packs everything together"],
    12: ["ventilated back panel reduces sweat on hot days",
         "hydration sleeve and hose port",
         "rain cover tucked in the base pocket",
         "padded hip belt with zip pockets"],
    13: ["adjustable torso length for a custom fit",
         "load lifters carry heavy loads comfortably for multi-day trips",
         "top lid converts into a summit pack",
         "large front stretch pocket for wet layers",
         "frame sheet transfers weight to the hips"],
    14: ["rechargeable battery with USB-C charging",
         "red night-vision mode preserves dark adaptation",
         "waterproof to IPX7 for storms and river crossings",
         "reactive lighting adjusts brightness automatically",
         "long burn time for multi-day trips"],
    15: ["preloaded topographic maps for offline navigation",
         "satellite messaging and SOS for remote areas",
         "multi-band GNSS improves accuracy in deep valleys",
         "long battery life in expedition mode"],
    16: ["adjustable leg loops fit over winter layers",
         "four gear loops for trad racks",
         "lightweight design for alpine climbing",
         "durable belay loop with wear indicator"],
    17: ["dry-treated sheath and core for wet and icy conditions",
         "middle mark helps find the center for rappels",
         "thin diameter for light alpine routes",
         "durable sheath for top-rope sessions at the crag"],
    18: ["hollow-fiber filter removes bacteria and protozoa",
         "squeeze design works with soft flasks",
         "gravity system filters water for a whole group",
         "backflush to restore flow rate in the field"],
}

# Review phrases per category: (positive aspects, negative aspects)
REVIEW_ASPECTS = {
    1: (["kept my feet completely dry crossing streams",
         "broke in quickly with no blisters",
         "great ankle support on rocky descents",
         "grip on wet granite is excellent",
         "comfortable for 25 km days with a full pack"],
        ["started leaking after a few weeks of rain",
         "sizing runs small, order half a size up",
         "the sole began peeling after one season",
         "too stiff and heavy for summer day hikes"]),
    2: (["light and fast on muddy forest trails",
         "drains water quickly after river crossings",
         "the rock plate saved my feet on sharp scree",
         "cushioning is great for long trail races"],
        ["mesh tore near the toe after 200 km",
         "lugs wore down very fast on asphalt",
         "narrow toe box gave me black toenails",
         "not waterproof, feet got cold in wet snow"]),
    3: (["perfect for river walks and wet rocks",
         "comfortable straight out of the box",
         "dries quickly at the campsite"],
        ["straps rubbed and caused blisters",
         "footbed got slippery when wet",
         "buckle broke on the second trip"]),
    4: (["stayed dry in a full day of heavy rain",
         "pit zips are great on steep climbs",
         "packs down small in my daypack",
         "hood fits over a climbing helmet"],
        ["wetted out after a few hours of rain",
         "felt clammy and not breathable at all",
         "the zipper jammed constantly",
         "cut is very boxy and the sleeves are short"]),
    5: (["incredibly warm for its weight",
         "kept me warm at minus fifteen in the wind",
         "packs into its own pocket",
         "perfect layer for cold belays"],
        ["down feathers leak through the seams",
         "lost loft after getting wet",
         "too warm for active hiking",
         "fabric snagged on branches and tore"]),
    6: (["no odor even after five days on trail",
         "soft merino that does not itch",
         "wicks sweat well on big climbs"],
        ["holes appeared after a few washes",
         "shrank in the dryer",
         "too thin for winter use"]),
    7: (["stretchy enough for scrambling",
         "the zip-off legs are handy on hot afternoons",
         "dries quickly after rain"],
        ["seams split at the crotch",
         "pockets are too shallow for a phone",
         "fabric pills after a few hikes"]),
    8: (["survived a storm with strong wind on an exposed ridge",
         "easy to pitch alone in the dark",
         "lots of room for two people and gear",
         "stayed dry inside during heavy rain"],
        ["condensation inside every morning",
         "a pole snapped in moderate wind",
         "the fly leaked at the seams",
         "heavier than advertised"]),
    9: (["warm and cozy on frosty nights",
         "compresses small for backpacking",
         "the hood cinch keeps the warmth in"],
        ["cold at the advertised comfort rating",
         "zipper snags on the liner",
         "lost loft after one season"]),
    10: (["finally slept warm on frozen ground",
          "quiet and comfortable for side sleepers",
          "inflates fast with the pump sack"],
         ["deflated overnight because of a slow leak",
          "crinkly and noisy every time I moved",
          "valve broke on the third night"]),
    11: (["boils water really fast",
          "works well in cold mornings",
          "the igniter lights every time"],
         ["struggles in wind without a screen",
          "igniter stopped working after a month",
          "pot support feels unstable"]),
    12: (["comfortable on hot summer hikes",
          "hip belt pockets fit snacks and a phone",
          "the rain cover is a nice touch"],
         ["back panel gets sweaty",
          "shoulder straps dig in with heavier loads",
          "zipper pull broke off"]),
    13: (["carries a heavy load comfortably for a week",
          "adjustable torso gives a perfect fit",
          "the lid converts to a summit pack"],
         ["hip belt buckle cracked on day two",
          "too heavy for ultralight hikers",
          "frame sheet bends under heavy loads"]),
    14: (["very bright and the battery lasts all night",
          "red mode is great in camp",
          "survived a downpour without issues",
          "charges fast over USB-C"],
         ["battery dies quickly in cold weather",
          "will not charge after a few weeks",
          "the headband stretched out",
          "flickers on low setting"]),
    15: (["accurate tracking even in deep valleys",
          "satellite messaging gave my family peace of mind",
          "battery lasted the whole expedition"],
         ["maps are hard to read in bright sun",
          "lost satellite fix in the forest",
          "the screen scratched easily"]),
    16: (["comfortable hanging belays",
          "gear loops are well placed",
          "fits nicely over winter layers"],
         ["leg loops are hard to adjust with gloves",
          "padding is too thin for big walls"]),
    17: (["handles nicely and feeds smoothly through the belay device",
          "dry treatment works on icy routes",
          "middle mark is very visible"],
         ["sheath fuzzed up quickly",
          "kinks a lot out of the bag",
          "stiff and hard to tie knots"]),
    18: (["clean tasting water from murky streams",
          "fast flow rate for a whole group",
          "backflushing restores the flow"],
         ["clogged after a few liters of silty water",
          "the pouch tore at the seam",
          "flow rate is painfully slow"]),
}

REVIEW_OPENERS_POS = ["Used this on a week in the mountains.", "Bought it for a trip to Lapland.",
                      "Tested on the Kungsleden trail.", "Took it hiking in the Tatras.",
                      "Great purchase for our family camping trip.", "Used it all summer in the Alps."]
REVIEW_OPENERS_NEG = ["Disappointed with this one.", "Wanted to love it but no.",
                      "Returned after a short trip.", "Expected better at this price.",
                      "Mixed feelings after a month."]
REVIEW_CLOSERS_POS = ["Would buy again.", "Highly recommend.", "Worth every euro.", "Five stars from me."]
REVIEW_CLOSERS_NEG = ["Would not buy again.", "Look elsewhere.", "Customer support was slow.",
                      "Hoping the replacement is better."]

TITLES_BY_RATING = {
    5: ["Excellent", "Best gear I own", "Exceeded expectations", "Trail tested and loved"],
    4: ["Very good", "Solid choice", "Happy with it", "Great with minor quirks"],
    3: ["Okay", "Average", "Does the job", "Mixed bag"],
    2: ["Not great", "Disappointing", "Below expectations"],
    1: ["Terrible", "Broke quickly", "Avoid", "Waste of money"],
}

TICKET_TEMPLATES = [
    ("Order not delivered", "My order {order} has not arrived yet. Tracking has not updated for 5 days. Please call me at {phone}."),
    ("Wrong size received", "I ordered size {size} but received a different size in order {order}. How do I exchange it?"),
    ("Zipper broke", "The main zipper on my {product} broke after two trips. Order reference {order}."),
    ("Refund request", "I returned {product} two weeks ago (order {order}) and still have no refund. Contact me at {email}."),
    ("Warranty claim", "The {product} failed during a trip. Is this covered by warranty? Original order {order}."),
    ("Leaking product", "My {product} leaks in heavy rain. Order {order}. Please advise."),
    ("Charging issue", "The {product} will not charge anymore with any USB-C cable. Order {order}."),
    ("Change delivery address", "Please change the delivery address for order {order}. New phone: {phone}."),
    ("Question about sizing", "What size of {product} should I pick if I usually wear {size}?"),
    ("Damaged on arrival", "The box was crushed and the {product} is damaged. Order {order}. Email me at {email}."),
]

SEARCH_TERMS = [
    "waterproof boots", "trail running shoes", "rain jacket", "down jacket", "merino base layer",
    "2 person tent", "4 season tent", "sleeping bag -10", "sleeping pad r-value", "camping stove",
    "daypack 25l", "backpack 60l", "headlamp usb-c", "gps satellite messenger", "climbing harness",
    "dry rope 9.5", "water filter", "zip off pants", "kids hiking boots", "ultralight tent",
]

FIRST_NAMES = [
    "Janis", "Anna", "Martins", "Liga", "Andris", "Ilze", "Toms", "Elina", "Karlis", "Laura",
    "Mantas", "Ruta", "Jonas", "Egle", "Lukas", "Greta", "Tanel", "Kadri", "Mart", "Liis",
    "Mikko", "Aino", "Juha", "Emilia", "Erik", "Sofia", "Lars", "Ingrid", "Nils", "Astrid",
    "Ole", "Kari", "Magnus", "Ida", "Felix", "Lena", "Jonas", "Mia", "Tobias", "Hannah",
    "Piotr", "Katarzyna", "Jakub", "Zofia", "Tomasz", "Agnieszka", "Florian", "Julia",
    "Maximilian", "Clara", "Sebastian", "Marie", "David", "Sara", "Oskar", "Alma",
]

LAST_NAMES = [
    "Berzins", "Kalnins", "Ozolins", "Jansons", "Liepa", "Krumins", "Petraitis", "Kazlauskas",
    "Jankauskas", "Tamm", "Saar", "Sepp", "Magi", "Korhonen", "Virtanen", "Makinen", "Nieminen",
    "Andersson", "Johansson", "Karlsson", "Nilsson", "Hansen", "Johansen", "Olsen", "Larsen",
    "Muller", "Schmidt", "Schneider", "Fischer", "Weber", "Wagner", "Nowak", "Kowalski",
    "Wisniewski", "Wojcik", "Kaminski", "Gruber", "Huber", "Bauer", "Steiner", "Hofer",
]
